title = "Aşkın Özgür"
baseURL = "https://askin.ws"
# theme = "hugo-researcher"
theme = "hugo-PaperMod"
enableEmoji = true
math = false          # enable KaTeX (https://katex.org/) globally
googleAnalytics = ""  # add your tracking id
languageCode = "tr-TR"

[taxonomies]
  tag = "tags"
  category = "categories"


[params]
  description = ".... description"
  favicon = "favicon.ico"  # path to a .ico to use as favicon
  logo = ""  # url or path to a logo to put in the header
  disableSpecial1stPost = true
  displayFullLangName = true
  showPostNavLinks = true
  showBreadCrumbs = true
  showCodeCopyButtons = true
  showRssButtonInSectionTermList =  true
  showToc = true
  showTitle = true
  
  [params.footer]
    text = "By Aşkın Özgür"
    url = "https://github.com/askin"
  [params.style]  # appearance options (can be omitted)
    fontFamily = "Inconsolata"
    pageWidth = "750px"
    avatarSize = "90px"
    colorBlack = "#222222"
    colorRed = "#dc3545"
  [[params.socialIcons]]
    icon = "fab fa-twitter"
    title = "Twitter"
    url = "https://twitter.com/kelebeks"
  [[params.socialIcons]]
    icon = "fas fa-envelope"
    title = "E-mail"
    url = "mailto:askin@askin.ws"
  [[params.socialIcons]]
    icon = "fab fa-facebook"
    title= "Facebook"
    url = "https://www.facebook.com/askin.yollu"
  [[params.socialIcons]]
    icon = "fab fa-github"
    title = "Github"
    url = "https://github.com/askin"
  [[params.socialIcons]]
    icon = "fab fa-gitlab"
    title = "Gitlab"
    url = "https://gitlab.com/askinozgur"
  [[params.socialIcons]]
    icon = "fab fa-bitbucket"
    title = "Bitbucket"
    url = "https://bitbucket.org/askin/"
  [[params.socialIcons]]
    icon = "fab fa-linkedin"
    title = "Linked In"
    url = "https://www.linkedin.com/in/askinozgur/"
  [[params.socialIcons]]
    icon = "fab fa-telegram"
    title = "Telegram"
    url = "https://telegram.me/kelebeks"
  [[params.socialIcons]]
    icon = "fab fa-docker"
    title = "Docker Hub"
    url = "https://hub.docker.com/u/askinozgur"
  [[params.socialIcons]]
    icon = "fab fa-hackerrank"
    title = "HackerRank"
    url = "https://www.hackerrank.com/askin"

[permalinks]
  "/" = "/:filename"

[menu]
  [[menu.main]]
    name = "Hakkımda"
    url = "/hakkimda"
    weight = 1

  [[menu.main]]
    name = "Blog"
    url = "/blog"
    weight = 2

  [[menu.main]]
    name = "Archives"
    url = "/archives"
    weight = 3

  [[menu.main]]
    name = "Öz Geçmiş"
    url = "/resume"
    # 'pre' and 'post' hooks are available
    # here we use an icon from Bootstrap https://icons.getbootstrap.com/
    pre = '<svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-file-earmark-person-fill" fill="currentColor" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M2 2a2 2 0 0 1 2-2h5.293A1 1 0 0 1 10 .293L13.707 4a1 1 0 0 1 .293.707V14a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2V2zm7.5 1.5v-2l3 3h-2a1 1 0 0 1-1-1zM11 8a3 3 0 1 1-6 0 3 3 0 0 1 6 0zm2 5.755S12 12 8 12s-5 1.755-5 1.755V14a1 1 0 0 0 1 1h8a1 1 0 0 0 1-1v-.245z"/></svg> '
    weight = 4

  # [[menu.main]]
  #   name = "Eksikler"
  #   url = "/eksikler"
  #   weight = 10000000

  [[menu.main]]
    name = "Tags"
    identifier = "tags"
    weight = 5
    url = "/tags/"

  
[markup.goldmark.renderer]
  unsafe = true  # allow raw HTML in markdown files
