title = "Aşkın Özgür"
baseURL = "https://askin.ws"
# theme = "hugo-researcher"
theme = "hugo-PaperMod"
enableEmoji = true
math = false          # enable KaTeX (https://katex.org/) globally
googleAnalytics = "G-LQCQ6JYDFR"
disqusShortname = "askin-ozgurun-web-gunlugu"
defaultContentLanguage = "en"
paginate = 10

[outputs]
  home = ['HTML', 'AMP', 'RSS', 'JSON']


[taxonomies]
  tag = "tags"
  category = "categories"

[Social]
  website = "https://askin.ws"
  email = "askin@askin.ws"
  facebook = "askinyollu"
  github = "askin"
  gitlab = "askinozgur"
  bitbucket = "askin"
  twitter = "kelebeks"
  linkedin = "askinozgur"
  spotify = "kelebex"
  telegram = "kelebeks"

[params]
  description = "Aşkın Özgür'ün Web Günlüğü ve Kişisel Sitesi"
  disableSpecial1stPost = true
  displayFullLangName = true
  showPostNavLinks = true
  showBreadCrumbs = true
  showCodeCopyButtons = true
  showRssButtonInSectionTermList =  true
  showToc = true
  showTitle = true
  isproduction = true

  [params.work]
      title = "Senior Software Developer"
      company = "Rise Technology"
      url = "https://www.rise-consulting.net/"

  [params.assets]
      favicon32x32 = "uploads/avatar.png"
      favicon16x16 = "uploads/avatar.png"
      apple_touch_icon = "uploads/avatar.png"
      safari_pinned_tab = "uploads/avatar.png"

  [[params.socialIcons]]
    name = "email"
    url = "mailto:askin@askin.ws"
  [[params.socialIcons]]
    name = "Telegram"
    url = "https://telegram.me/kelebeks"

  [[params.socialIcons]]
    name = "Twitter"
    url = "https://twitter.com/kelebeks"
  [[params.socialIcons]]
    name = "Facebook"
    url = "https://www.facebook.com/askin.yollu"
  [[params.socialIcons]]
    name = "Instagram"
    url = "https://instagram.com/askinozguur/"
  [[params.socialIcons]]
    name = "spotify"
    url = "https://open.spotify.com/user/kelebex"
  [[params.socialIcons]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/askinozgur/"

  [[params.socialIcons]]
    name = "Github"
    url = "https://github.com/askin"
  [[params.socialIcons]]
    title = "Gitlab"
    name = "Gitlab"
    url = "https://gitlab.com/askinozgur"
  [[params.socialIcons]]
    name = "Bitbucket"
    url = "https://bitbucket.org/askin/"


  [[params.socialIcons]]
    name = "docker"
    url = "https://hub.docker.com/u/askinozgur"
  [[params.socialIcons]]
    name = "hackerrank"
    url = "https://www.hackerrank.com/askin"
  [[params.socialIcons]]
    name = "lichess"
    url = "https://lichess.org/@/kelebeks"

[languages]
  [languages.tr]
    description = "Aşkın Özgür'ün Web Günlüğü ve Kişisel Sitesi"

    languageName = "Türkçe :tr:"
    languageAltTitle = "Türkçe"

    [[languages.tr.menu.main]]
      name = "Hakkımda"
      url = "/hakkimda"
      weight = 1

    [[languages.tr.menu.main]]
      name = "Blog - tr"
      url = "/tr/blog"
      weight = 2

    [[languages.tr.menu.main]]
      name = "Blog - en"
      url = "../blog"
      weight = 3

    [[languages.tr.menu.main]]
      name = "Arşiv"
      url = "/arsiv"
      weight = 4

    [[languages.tr.menu.main]]
      name = "Öz Geçmiş"
      url = "../resume/index-tr.html"
      pre = '<svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-file-earmark-person-fill" fill="currentColor" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M2 2a2 2 0 0 1 2-2h5.293A1 1 0 0 1 10 .293L13.707 4a1 1 0 0 1 .293.707V14a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2V2zm7.5 1.5v-2l3 3h-2a1 1 0 0 1-1-1zM11 8a3 3 0 1 1-6 0 3 3 0 0 1 6 0zm2 5.755S12 12 8 12s-5 1.755-5 1.755V14a1 1 0 0 0 1 1h8a1 1 0 0 0 1-1v-.245z"/></svg> '
      weight = 5

    [[languages.tr.menu.main]]
      name = "Etiketler"
      identifier = "tags"
      weight = 6
      url = "/tags/"

    [[languages.tr.menu.main]]
      name = "Arama"
      identifier = "arama"
      weight = 7
      url = "arama/"

  [languages.en]
    description = "Aşkın Özgür's Web Blog and Personal Page"

    languageName = "English :us:"
    languageAltTitle = "English"

    [[languages.en.menu.main]]
      name = "About Me"
      url = "/aboutme"
      weight = 1

    [[languages.en.menu.main]]
      name = "Blog - tr"
      url = "/tr/blog/"
      weight = 2

    [[languages.en.menu.main]]
      name = "Blog - en"
      url = "/blog"
      weight = 3

    [[languages.en.menu.main]]
      name = "Archive"
      url = "/archives"
      weight = 4

    [[languages.en.menu.main]]
      name = "Resume"
      url = "/resume"
      pre = '<svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-file-earmark-person-fill" fill="currentColor" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M2 2a2 2 0 0 1 2-2h5.293A1 1 0 0 1 10 .293L13.707 4a1 1 0 0 1 .293.707V14a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2V2zm7.5 1.5v-2l3 3h-2a1 1 0 0 1-1-1zM11 8a3 3 0 1 1-6 0 3 3 0 0 1 6 0zm2 5.755S12 12 8 12s-5 1.755-5 1.755V14a1 1 0 0 0 1 1h8a1 1 0 0 0 1-1v-.245z"/></svg> '
      weight = 5

    [[languages.en.menu.main]]
      name = "Tags"
      identifier = "tags"
      weight = 6
      url = "/tags/"

    [[languages.en.menu.main]]
      name = "Search"
      identifier = "search"
      weight = 7
      url = "search/"

[markup.goldmark.renderer]
  unsafe = true  # allow raw HTML in markdown files
